= 数据中台
:toc:
:setnums:

数据中台由业务驱动, 主要解决业务问题.

数据中台是 聚合和治理跨域数据, 将数据抽象封装成服务, 连接
前台(业务端)与后台(数据平台), 提供给前台以业务价值的抽象概念.

// TODO 中台完善后添加到这里
具体参考 中台

如下内容参考
link:https://www.jiqizhixin.com/articles/2019-04-23-4[数据中台演进的四个阶段-阿里]

数据中台是如何赋能业务使用数据的例子如下

现在大家可能都认识到了统一消费者数据的必要性, 但是在几年前,
哪怕是在阿里巴巴, 消费者的信息也分散在各个业务中, 碎片化,散点化, 
而业务当时需要把这些分散的人的数据集中起来, 进行人群画像.
道理很明白, 人群画像越清晰, 服务就会越精准.

怎么统一消费者数据?

首先, 定义埋点规范, 同一个人就用同一个标识, ID打通, 也就是所谓的One ID.

其次, 还会碰上一家人使用一个登录帐号的问题, 那么就需要建立同人的数据模型, 通过一些方式, 比如, IP网段是不是一样, 来分辨出具体的那个人, 建立AID（Alibaba ID）;

再次, 每个人还有各种网络行为, 要如何把这些行为结构化, 装到各种框架里面？这个特别难, 我们当时主要是跟人类学家合作, 一起把行为的分类树做出来. 这个分类树非常细, 甚至能够把一个人的发质都结构化了. 

最后, 就需要通过算法模型, 把所有的标签都贴回到人上面. 

== 中台具备的三大能力
=== 数据模型能力
在业务层面, 业务抽象能够解决80%的共性问题, 开放的系统架构来解决20%的个性问题, 但同时又要把平台上的业务逻辑分开, 因为不同的业务逻辑之间可能有冲突. 

这在数据中台就表现为数据的中心化, 也就是数据的高内聚、低耦合, 需要对共性问题抽象出业务的规则, 建立数据模型, 一个好的内聚模块能够解决一个事情, 同时又要降低模块和模块之间的耦合度, 让模块具有良好的可读性和可维护性. 

这里的前提是要有真正懂业务能沉淀经验的人, 以及要在企业层面开展数据治理, 让数据能够准确、适度共享、安全地被使用. 

=== AI算法模型能力
要实现数据业务化, 前提是做到数据的资产化. 要能够从数据原油里面, 去提炼出可以使用的汽油. 

比如说数据的标签化, 背后就有投入产出比的考量：通过标签, 广告主可以非常方便快捷地去建立自己的人群包, 实现精准营销, 同时投放的ROI也是可见的、透明的, 广告主可以自己去评估数据资产的使用情况. 

=== 数据业务化能力
和数据中心化类似, 数据业务化也需要很强的行业经验来指导, 建立合适的业务场景, 在场景里面去使用数据, 从而体现数据的价值, 来大大扩展数据在行业中的应用能力. 

在奇点云和某酒类客户的合作过程中, 我们最大的收获不是帮助客户完成了数据中台的搭建, 而是通过理解客户的业务, 把其经验沉淀到数据中台, 从而赋能客户更多的端上的创新业务, 带来了生意的增量. 

最后总结一下, 未来的数据中台最重要的不单是数据的存储和计算能力, 而是要能从「存、通、用」的角度和业务结合, 帮助企业从数据中获取价值, 沉淀数据资产, 最终用数据赚钱

