= 数据平台
:toc:
:setnums:

WARNING: 技术发展很快, 术语也在不停的变化. 要了解术语, 但是
  更要了解术语背后的意义, 不要沉迷与术语/概念, 因噎废食.


// TODO 数据平台完善+准确的定义
数据平台是

.随着中台概念的兴起, 原数据平台也可以区分为两个领域
. 数据中台, 负责解决业务问题
. 数据平台, 负责解决技术问题

本文会涉及到数据中台, 但数据中台具体介绍参考 
link:./middle_platform.adoc[数据中台]

== 数据平台的发展
WARNING: 注意不要陷入概念之中. 对于其中的某些概念不同的人
  理解可能不同, 理解整体意思就可以了, 不要 因噎废食.

数据平台的发展与企业数据规模的扩大和对BI需求变强有关.

从企业发展角度看, 数据平台的发展流程一般分为如下四个阶段.

需要注意的是, 在真实情况中, 各阶段可能是混合存在的,
而不是泾渭分明. 重要的是理解数据发展的大概历史和过程.

数据库阶段::
  主要是解决业务人员工作中需要的报表footnote:[也可以理解为统计指标].
  从数据库等工具导出业务人员需要的报表, 如统计交易笔数等. +
  这一阶段主要是单一业务系统, 以OLTP footnote:[联机事务处理]为主.

数据仓库阶段(过渡阶段)::
  借助数据仓库/数据湖等手段统一存储来自一个或多个不同源的集成数据
  的中央存储库. +
  对部分业务的数据进行采集, 整理, 分析, 展现, 按照业务生成多维度
  的报表, 为业务提供数据上的指引, 帮助领导者做决策. +
  随着业务规模扩大, 这一阶段对BI和报表的需求更复杂更强烈, 数据量
  也更大, 数据分析以OLAP footnote:[联机分析处理]为主.

数据平台阶段::
  在数据平台阶段, 数据平提案有完整的体系和流程去满足业务的数据需求.
  在这个阶段, 主要是解决数据平台的技术问题.
  数据仓库阶段与数据平台阶段的主要区别是, 数据仓库是一个过渡阶段, 
  对技术的使用仅仅为了满足业务, 没有形成一套体系, 一个平台.
+
.常见问题如下
. 系统架构设计
. 系统性能优化
. OLTP和OLAP连通处理的能力.
. 业务快速接入数据平台的能力(API/SDK)
. 业务快速建立数据模型的能力(API/SDK), 业务人员不需要了解技术,
  根据需求就可以快速创建模型. 如业务人员输入相应的条件, 数据平台
  自动计算出相应的指标.
. 可视化展现/生成报表 的能力(API/SDK)

数据中台::
  对整个企业的数据进行采集, 整理, 分析, 展现, 并且构建数据模型.
  能够提供跨部门的, 多业务一致的报表数据, 并能提供数据上的指引, 
  帮助领导者做决策. +
  数据中台阶段与数据平台的主要区别时, 数据中台强调数据业务化的能力,
  强调整合公司整体资源的能力, 包括设计统一的数据模型, 埋点规范,
  业务模型等. 而数据平台仅仅提供技术支撑, 业务分析/建模还是由
  业务团队负责. 如 数据中台负责在各业务间实现用户统一ID(oneID).
  具体参考 link:./middle_platform.adoc[数据中台]

//-

中台/平台都是比较新的概念, 随着时间改变也可能产生变化, 
大家尽量理解其含义吧, 最主要的是理解中台/平台在业务/架构**领域**上的划分.

举个例子大家可能明白的更清晰些

.企业A的数据平台之路
. 假设企业A是卖产品的, 数据需求只有用户信息和订单信息.
. 数据库阶段: 在初创阶段, 公司只需要 Mysql/Redis 等就可以满足需求. 
  报表可以通过查询数据库生成. 各种指标(如客单价)也可以.

. 数据仓库阶段: 随着公司规模扩大, 公司已经有几十亿历史订单数据, 
  每日交易量也接近千万笔, Mysql 已经不堪重负, 公司决定使用 es/hive
  存储交易数据, 每日从中计算各种指标, 生成报表.

. 数据平台阶段: 公司规模进一步扩大, 目前公司不止有交易数据, 还有
  外卖数据, 评论数据等, 这时公司决定成立数据平台组, 为各业务组提供
  数据支持. 比如流程为
  .. 业务组按照数据平台约定的格式, 将数据交付到数据平台. 或者单独与
    数据平台协商数据交付方式(非规范数据时)
  .. 数据采集完毕后, 业务组按照数据平台约定的格式计算指标, 生成报表.
    如数据平台提供SQL查询方式获取指标.
  .. 或者业务组与数据平台组协商, 让数据平台组协助计算某些指标.

. 数据中台阶段: 假设交易业务和外卖业务分别属于不同的团队, 各自有各自的
  用户表, 如此导致他们没有**数据互通**. 此时数据中台可以提供给业务团队一个
  统一的用户录入和查询API, 通过中台, 我们可以看到同一个用户的外卖数据和
  交易数据, 从而得到更精确/详细的用户画像. 可以看到, 相较于数据平台, 
  数据中台一方面连通了各业务线, 使数据发挥更大的价值, 另一方面也减少了
  各业务团队的重复工作量. 当然, 中台的作用可能远不止此, 具体参考
  link:./middle_platform.adoc[数据中台]

== 数据平台的架构
.从技术上看, 按照分层架构, 数据平台可以分为三层
. 数据采集
. 数据存储. 又称为 数据仓库, 数据湖等.
. 数据分析. 又称为 数据集市 等.
. 数据展现

IMPORTANT: 在一切开始之前, 我们应当十分清楚, 数据平台是为了
  服务与业务需求, 为了发现数据的价值. +
  所以, 在搭建数据平台之前, 我们应当先了解业务, 建立合适的
  数据模型. +
  如对于用户数据, 我们应当在各业务线打通用户数据, 找到 oneID.

=== 数据采集
数据是重中之重, 好的数据来源是成功的一半.

.数据采集有两种方式
业务方主动上报::
  数据平台应当提供便捷的API帮助业务方进行数据上报.

数据迁移::
  即 <<etl, 数据迁移>>, 数据平台负责业务数据的导入.

=== 数据存储
.根据数据/业务属性选择合适的存储介质
. 关系数据库. 如mysql. 一般是业务直接使用的数据库.
. <<ods, 操作型数据存储>>, 最近一段时间内, 实时的且可操作的数据.
. <<data_warehouse, 数据仓库>>, 统一存储各数据源的结构化数据.
. <<data_lake, 数据湖>>, 统一存储各数据源的结构化/非结构化数据,
  分别进行分析.

=== 数据分析
通过spark/pandas等工具分析数据.

.常用用法
. 根据业务需求, 计算指标
. 了解 业务/数据 常用的模型, 建立 数据/业务 模型.
. 深入了解业务, 挖掘数据价值, 分析/发现模型.

=== 数据展现
生成报表或者可视化图标展现给他人.

[[concept]]
== 概念
[[etl]]
=== ETL
ETL Extract-Transform-Load, 用于描述数据迁移的几个过程.

.ETL过程
. Extract: 从数据源读取数据.
. Transform: 数据清洗, 转换.
. Load: 数据导入到目标仓库, 如 Hive.

.Extract实现
. Sqoop批量导入
. 通过 binlog 等方式读取Mysql数据
. 所有数据通过 kafka 获取(需要业务方配合)

[[ods]]
=== ODS
ODS Operational Data Store, 操作性数据, 数据库到数据仓库的一种过渡.

ODS存储的是当前的数据情况, 给使用者提供当前的状态, 提供即时性的, 
操作性的, 集成的全体信息的需求.

一般而言, ODS 数据是最近一段时间的实时数据, 可以被更改.
数据仓库数据是永久的历史数据, 不可被更改, 只能通过version判断最新数据.

[[data_mark]]
=== Data Mark
DM, Data Mark, 数据集市, 面向应用, 为业务/应用提供具体的数据分析, 数据指标.

[[data_warehouse]]
=== Data Warehouse
DW, Data Warehouse, 数据仓库.

数据仓库是来自一个或多个不同源的集成数据的中央存储库.
数据仓库将当前和历史数据存储在一起, 用于为整个企业的员工创建分析报告.

数据仓库一般存储结构化数据, 对数据进行统一分析.

[[data_lake]]
=== Data Lake
Data Lake, 数据湖.

数据湖是一个集中式存储库, 允许以任意规模存储所有结构化和非结构化数据.

可以按原样存储数据(无需先对数据进行结构化处理), 并运行不同类型的分析:
从控制面板和可视化到大数据处理, 实时分析和机器学习, 以指导做出更好的决策.

参考 https://aws.amazon.com/cn/big-data/datalakes-and-analytics/what-is-a-data-lake[aws:data lake]

[[bi]]
== BI
BI, Business Intelligence, 商业智能.

指用现代数据仓库技术, 线上分析处理技术, 数据挖掘和数据展现技术
进行数据分析以实现商业价值.

== 参考
. link:https://www.jiqizhixin.com/articles/2019-04-23-4[数据中台演进的四个阶段-阿里]

